### ISSUE TITLE
Very Nice Example spiral arm notebook.  Worked perfectly

### ISSUE THREAD

**Issue by glangsto** [editeodoro/DHmodels#1]
So this is not really an issue, but I didn't know where to put my compliment.  
Your notebook worked very well.  All the required code and data were readily available.
Thanks

I did add a couple lines to avoid a warning in DHmodels.py, but after I added the diagnostic
message the warning disappeared. The warning concerned computing log10()

So this is probably not necessary.

My temporary changes for your review:
your:
            logN = np.log10(np.nansum(N))

goes to:

            Nsum = np.nansum(N)
            print("Min,Max,Median Sums: %7.1f, %7.f, %7.1f" % (min(Nsum), max(Nsum), np.median(Nsum)))
            logN = np.log10(Nsum)

**Comment by editeodoro** [comment]
Hi Glen, 
thanks, I am glad you liked this notebook! Thanks for your suggestion, I will update the code accordingly to avoid those warnings.

Cheers, 
Enrico
